services:
  mysql:
    image: mysql:8.4
    container_name: reservation-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: reservation123!
      MYSQL_DATABASE: reservation
    volumes:
      - ./mysql-init.d:/docker-entrypoint-initdb.d
    networks:
      - reservation-network

  redis:
    image: redis:8.2
    container_name: reservation-redis
    ports:
      - "6379:6379"
    networks:
      - reservation-network

networks:
  reservation-network:
    driver: bridge
    name: reservation-network